version: '3'
services:
  app:
    image: golang:latest
    command: go run app/server.go
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/go
    environment:
      - "GOPATH="
    links:
      - mysql:db
  mysql:
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3326:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_example
